<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpaBookingSystem.ApplicationCore\SpaBookingSystem.ApplicationCore.csproj" />
    <ProjectReference Include="..\SpaBookingSystem.DataLayer\SpaBookingSystem.DataLayer.csproj" />
  </ItemGroup>

</Project>
